package forge.gamesimulationtests;

import forge.game.Game;
import forge.game.ability.AbilityKey;
import forge.game.card.Card;
import forge.game.card.CounterEnumType;
import forge.game.player.Player;
import forge.game.spellability.SpellAbility;
import forge.game.zone.ZoneType;
import org.testng.AssertJUnit;
import org.testng.annotations.Test;

/**
 * Tests for ChangesZone trigger timing, verifying that creatures returning
 * from exile (e.g. via Brutal Cathar, Fiend Hunter) do not see deaths that
 * happened as part of the same event that caused them to return.
 *
 * Rewrites the regression canaries from PR #9484 to use the UI code path
 * via PlayerControllerForTests instead of the AI simulation path.
 */
public class ChangesZoneTriggerTest extends UIPathTest {

    // In resetGame(), player index 1 ("p1") is the active player in MAIN1.
    // Use p1 as the caster and p0 as the opponent throughout.

    /**
     * Resolve the stack, including any triggers generated by SBAs (lethal
     * damage deaths) and by zone-change events during resolution.
     *
     * The base {@code playUntilStackClear} exits as soon as the stack is
     * empty, but SBA-caused deaths and their triggers haven't been processed
     * yet at that point.  This override keeps looping until the stack has
     * been empty for two consecutive mainLoopSteps, which guarantees that
     * SBAs have run and no new triggers were generated.
     */
    @Override
    protected void playUntilStackClear(Game game) {
        int consecutiveEmpty = 0;
        for (int i = 0; i < 200 && !game.isGameOver(); i++) {
            game.getPhaseHandler().mainLoopStep();
            if (game.getStack().isEmpty()
                    && !game.getStack().hasSimultaneousStackEntries()) {
                consecutiveEmpty++;
                if (consecutiveEmpty >= 2) {
                    return;
                }
            } else {
                consecutiveEmpty = 0;
            }
        }
    }

    // --- Helpers ---

    private void castWithTarget(Game game, Player p, Card spell, Card target) {
        SpellAbility sa = spell.getFirstSpellAbility();
        AssertJUnit.assertNotNull(spell.getName() + " should have a spell ability", sa);
        sa.getTargets().add(target);
        AssertJUnit.assertTrue("Should be able to cast " + spell.getName(),
                castSpell(p, sa));
        playUntilStackClear(game);
    }

    private void castNoTarget(Game game, Player p, Card spell) {
        SpellAbility sa = spell.getFirstSpellAbility();
        AssertJUnit.assertNotNull(spell.getName() + " should have a spell ability", sa);
        AssertJUnit.assertTrue("Should be able to cast " + spell.getName(),
                castSpell(p, sa));
        playUntilStackClear(game);
    }

    private Card findCardInZone(Game game, String name, Player controller,
            ZoneType zone) {
        for (Card c : game.getCardsIn(zone)) {
            if (c.getName().equals(name)
                    && c.getController().equals(controller)) {
                return c;
            }
        }
        return null;
    }

    // --- Tests ---

    /**
     * Cast Brutal Cathar (exiles Slaughter Specialist), then Murder kills
     * Cathar. Specialist returns — it should have 0 +1/+1 counters because
     * it was not on the battlefield when Cathar died.
     */
    @Test
    public void testBrutalCatharDoesNotTriggerReturnedSlaughterSpecialist() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        addCard("Slaughter Specialist", opp);
        Card brutalCathar = addCardToZone("Brutal Cathar", p, ZoneType.Hand);

        // Cast Brutal Cathar — ETB auto-targets the only opponent creature
        castNoTarget(game, p, brutalCathar);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Exile));
        AssertJUnit.assertEquals(0, countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Battlefield));

        // Murder Cathar — Specialist returns from exile
        Card catharOnBoard = findCardWithName(game, "Brutal Cathar");
        AssertJUnit.assertNotNull(catharOnBoard);
        Card murder = addCardToZone("Murder", p, ZoneType.Hand);
        castWithTarget(game, p, murder, catharOnBoard);

        Card returnedSpecialist = findCardWithName(game,
                "Slaughter Specialist");
        AssertJUnit.assertNotNull(returnedSpecialist);
        AssertJUnit.assertEquals(0,
                returnedSpecialist.getCounters(CounterEnumType.P1P1));
    }

    /**
     * Shock kills an opponent creature while Slaughter Specialist is in play.
     * Specialist should get 1 +1/+1 counter.
     */
    @Test
    public void testSlaughterSpecialistTriggersForNormalDeath() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        addCard("Slaughter Specialist", p);
        Card goblin = addCard("Raging Goblin", opp);
        Card shock = addCardToZone("Shock", p, ZoneType.Hand);

        castWithTarget(game, p, shock, goblin);

        Card specialist = findCardWithName(game, "Slaughter Specialist");
        AssertJUnit.assertNotNull(specialist);
        AssertJUnit.assertEquals(1,
                specialist.getCounters(CounterEnumType.P1P1));
    }

    /**
     * Pyroclasm kills 2 opponent creatures while Slaughter Specialist is in
     * play. Specialist should get 2 +1/+1 counters.
     */
    @Test
    public void testSlaughterSpecialistTriggersForMultipleDeaths() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        addCard("Slaughter Specialist", p);
        addCard("Raging Goblin", opp);
        addCard("Raging Goblin", opp);
        Card pyroclasm = addCardToZone("Pyroclasm", p, ZoneType.Hand);

        castNoTarget(game, p, pyroclasm);

        Card specialist = findCardWithName(game, "Slaughter Specialist");
        AssertJUnit.assertNotNull(specialist);
        AssertJUnit.assertEquals(2,
                specialist.getCounters(CounterEnumType.P1P1));
    }

    /**
     * Cloudshift blinks Slaughter Specialist, then Shock kills an opponent
     * creature. The re-entered Specialist should still trigger and get a
     * counter.
     */
    @Test
    public void testSlaughterSpecialistTriggersAfterBlink() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        Card specialist = addCard("Slaughter Specialist", p);
        Card goblin = addCard("Raging Goblin", opp);
        Card cloudshift = addCardToZone("Cloudshift", p, ZoneType.Hand);

        castWithTarget(game, p, cloudshift, specialist);

        // Specialist re-entered; find it again
        Card blinkedSpecialist = findCardWithName(game,
                "Slaughter Specialist");
        AssertJUnit.assertNotNull(blinkedSpecialist);

        // Shock kills the opponent creature
        Card shock = addCardToZone("Shock", p, ZoneType.Hand);
        castWithTarget(game, p, shock, goblin);

        AssertJUnit.assertEquals(1,
                blinkedSpecialist.getCounters(CounterEnumType.P1P1));
    }

    /**
     * Shock kills Doomed Dissenter — should create a Zombie Token.
     */
    @Test
    public void testDoomedDissenterDiesTrigger() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);

        Card dissenter = addCard("Doomed Dissenter", p);
        Card shock = addCardToZone("Shock", p, ZoneType.Hand);

        castWithTarget(game, p, shock, dissenter);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Zombie Token", ZoneType.Battlefield));
    }

    /**
     * Unsummon bounces Subterranean Shambler — LTB trigger should deal 1
     * damage to each creature without flying, killing the opponent's
     * Raging Goblin.
     */
    @Test
    public void testLeavesBattlefieldToHandTrigger() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        Card shambler = addCard("Subterranean Shambler", p);
        addCard("Raging Goblin", opp);
        Card unsummon = addCardToZone("Unsummon", p, ZoneType.Hand);

        castWithTarget(game, p, unsummon, shambler);

        AssertJUnit.assertEquals(0, countCardsWithName(game,
                "Subterranean Shambler", ZoneType.Battlefield));
        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Subterranean Shambler", ZoneType.Hand));
        AssertJUnit.assertEquals(0, countCardsWithName(game,
                "Raging Goblin", ZoneType.Battlefield));
    }

    /**
     * Brutal Cathar exiles Slaughter Specialist. Then Pyroclasm kills Cathar
     * and Raging Goblin simultaneously. Specialist returns but should have
     * 0 counters — it was not on the battlefield when Goblin died.
     */
    @Test
    public void testBrutalCatharReturnDoesNotSeeSimultaneousDeaths() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        // Only Specialist on opponent's board so ETB auto-target works
        addCard("Slaughter Specialist", opp);
        Card brutalCathar = addCardToZone("Brutal Cathar", p, ZoneType.Hand);
        castNoTarget(game, p, brutalCathar);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Exile));

        // Add Goblin after Specialist is exiled
        addCard("Raging Goblin", opp);

        // Pyroclasm kills Cathar (2/2) and Goblin (1/1) simultaneously
        Card pyroclasm = addCardToZone("Pyroclasm", p, ZoneType.Hand);
        castNoTarget(game, p, pyroclasm);

        Card returnedSpecialist = findCardWithName(game,
                "Slaughter Specialist");
        AssertJUnit.assertNotNull(returnedSpecialist);
        AssertJUnit.assertEquals(0,
                returnedSpecialist.getCounters(CounterEnumType.P1P1));
    }

    /**
     * Cast Slaughter Specialist from hand — ETB trigger should create a
     * 1/1 Human token for each opponent. Verify the opponent has 1 creature.
     */
    @Test
    public void testSlaughterSpecialistEtbChangesZone() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        Card specialist = addCardToZone("Slaughter Specialist", p,
                ZoneType.Hand);
        castNoTarget(game, p, specialist);

        int oppCreatures = 0;
        for (Card c : opp.getCardsIn(ZoneType.Battlefield)) {
            if (c.isCreature()) {
                oppCreatures++;
            }
        }
        AssertJUnit.assertEquals(1, oppCreatures);
    }

    /**
     * Oubliette phases out opponent's Raging Goblin. Disenchant destroys
     * Oubliette — Goblin returns tapped.
     */
    @Test
    public void testOublietteReturnsCreatureOnDestroy() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        addCard("Raging Goblin", opp);
        Card oubliette = addCardToZone("Oubliette", p, ZoneType.Hand);
        castNoTarget(game, p, oubliette);

        // Disenchant destroys Oubliette — Goblin should return
        Card oublietteOnBoard = findCardWithName(game, "Oubliette");
        AssertJUnit.assertNotNull(oublietteOnBoard);
        Card disenchant = addCardToZone("Disenchant", p, ZoneType.Hand);
        castWithTarget(game, p, disenchant, oublietteOnBoard);

        Card returnedGoblin = findCardInZone(game, "Raging Goblin", opp,
                ZoneType.Battlefield);
        AssertJUnit.assertNotNull(returnedGoblin);
        AssertJUnit.assertFalse(returnedGoblin.isPhasedOut());
        AssertJUnit.assertTrue(returnedGoblin.isTapped());
    }

    /**
     * Murder kills Jotun Owl Keeper that has 2 age counters.
     * LKI counter value should produce 2 Bird Tokens.
     */
    @Test
    public void testJotunOwlKeeperLkiCounterDiesTrigger() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);

        Card owlKeeper = addCard("Jotun Owl Keeper", p);
        owlKeeper.addCounterInternal(CounterEnumType.AGE, 2, p, true,
                null, AbilityKey.newMap());
        AssertJUnit.assertEquals(2,
                owlKeeper.getCounters(CounterEnumType.AGE));
        Card murder = addCardToZone("Murder", p, ZoneType.Hand);

        castWithTarget(game, p, murder, owlKeeper);

        AssertJUnit.assertEquals(2, countCardsWithName(game,
                "Bird Token", ZoneType.Battlefield));
    }

    /**
     * Fiend Hunter exiles Slaughter Specialist. Day of Judgment destroys
     * all creatures (Hunter + Goblin die simultaneously). Specialist
     * returns but should have 0 counters — it was not on the battlefield
     * when Goblin died.
     */
    @Test
    public void testFiendHunterReturnDoesNotSeePastDeath() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        // Only Specialist on opponent's board so ETB auto-target works
        addCard("Slaughter Specialist", opp);
        Card fiendHunter = addCardToZone("Fiend Hunter", p, ZoneType.Hand);
        castNoTarget(game, p, fiendHunter);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Exile));

        // Add Goblin after exile
        addCard("Raging Goblin", opp);

        // Day of Judgment destroys all — Hunter (1/3) + Goblin (1/1) die
        Card wrath = addCardToZone("Day of Judgment", p, ZoneType.Hand);
        castNoTarget(game, p, wrath);

        int specialistOnBf = countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Battlefield);
        int specialistInExile = countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Exile);
        AssertJUnit.assertEquals(1, specialistOnBf + specialistInExile);
        if (specialistOnBf == 1) {
            Card returnedSpecialist = findCardWithName(game,
                    "Slaughter Specialist");
            AssertJUnit.assertNotNull(returnedSpecialist);
            AssertJUnit.assertEquals(0,
                    returnedSpecialist.getCounters(CounterEnumType.P1P1));
        }
    }

    /**
     * Banisher Priest exiles Slaughter Specialist. Shock kills Raging
     * Goblin, then Murder kills Priest. Specialist returns but should have
     * 0 counters — the Goblin death happened before Specialist returned.
     */
    @Test
    public void testBanisherPriestReturnDoesNotSeePastDeath() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        // Only Specialist on opponent's board so ETB auto-target works
        addCard("Slaughter Specialist", opp);
        Card banisherPriest = addCardToZone("Banisher Priest", p,
                ZoneType.Hand);
        castNoTarget(game, p, banisherPriest);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Slaughter Specialist", ZoneType.Exile));

        // Add Goblin after exile, then kill it with Shock
        Card goblin = addCard("Raging Goblin", opp);
        Card shock = addCardToZone("Shock", p, ZoneType.Hand);
        castWithTarget(game, p, shock, goblin);

        // Murder kills Priest — Specialist returns
        Card priestOnBoard = findCardWithName(game, "Banisher Priest");
        AssertJUnit.assertNotNull(priestOnBoard);
        Card murder = addCardToZone("Murder", p, ZoneType.Hand);
        castWithTarget(game, p, murder, priestOnBoard);

        Card returnedSpecialist = findCardWithName(game,
                "Slaughter Specialist");
        AssertJUnit.assertNotNull(returnedSpecialist);
        AssertJUnit.assertEquals(0,
                returnedSpecialist.getCounters(CounterEnumType.P1P1));
    }

    /**
     * Pyroclasm kills 2 opponent Raging Goblins while Poison-Tip Archer
     * is in play. Archer should trigger twice, dealing 2 damage total to
     * the opponent.
     */
    @Test
    public void testPoisonTipArcherSeesSimultaneousDeaths() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        addCard("Poison-Tip Archer", p);
        addCard("Raging Goblin", opp);
        addCard("Raging Goblin", opp);
        Card pyroclasm = addCardToZone("Pyroclasm", p, ZoneType.Hand);

        int oppLifeBefore = opp.getLife();

        castNoTarget(game, p, pyroclasm);

        AssertJUnit.assertEquals(0, countCardsWithName(game,
                "Raging Goblin", ZoneType.Battlefield));
        AssertJUnit.assertEquals(oppLifeBefore - 2, opp.getLife());
    }

    /**
     * Rest in Peace + Skyclave Apparition exiles an opponent creature.
     * Murder destroys Apparition — even though RIP replaces "dies" with
     * exile, the LTB trigger should still fire and create an Illusion Token.
     */
    @Test
    public void testTokenExiledByReplacementCountsAsLTB() {
        Game game = initAndCreateGame();
        Player p = game.getPlayers().get(1);
        Player opp = game.getPlayers().get(0);

        addCard("Rest in Peace", p);
        addCard("Raging Goblin", opp);
        Card skyclave = addCardToZone("Skyclave Apparition", p,
                ZoneType.Hand);
        castNoTarget(game, p, skyclave);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Raging Goblin", ZoneType.Exile));

        // Murder destroys Apparition — should create Illusion Token
        Card apparitionOnBoard = findCardWithName(game,
                "Skyclave Apparition");
        AssertJUnit.assertNotNull(apparitionOnBoard);
        Card murder = addCardToZone("Murder", p, ZoneType.Hand);
        castWithTarget(game, p, murder, apparitionOnBoard);

        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Illusion Token", ZoneType.Battlefield));
        AssertJUnit.assertEquals(1, countCardsWithName(game,
                "Skyclave Apparition", ZoneType.Exile));
    }
}
